const {test}=require('node:test');
const assert=require('node:assert/strict');
const {deflateRawSync}=require('node:zlib');
const R=require('../save-reader.js'),C=require('../core.js');
const be=n=>{const b=Buffer.alloc(4);b.writeUInt32BE(n>>>0);return b;};
const bytes=(...parts)=>Buffer.concat(parts.map(p=>Buffer.from(p)));
function metadata(name='Test world'){const text=Buffer.from(name);return bytes([9],be(42),be(0),be(12345),be(text.length),text,Buffer.alloc(105));}
function item(id=3157,quantity=12,slot=0,extra=false){return bytes(be(id),[0,1,2,0,55],Buffer.alloc(16,42),[0,8,1],be(id),be(quantity),[0,0,0,0],extra?bytes([0,24,1],be(100),be(2),[0,59,0],be(1),[0,7],be(4)):[],[0,12,0],be(slot),[255,255]);}
function player(inventory=[item()],armor=[]){const result=bytes([2,0,0,0,1],be(0),Buffer.alloc(120),[0,13,1],be(0),[1],be(36),be(inventory.length),...inventory,[1],be(4),be(armor.length),...armor,[0,41,1],Buffer.alloc(11),[31,0,0,0,0,0,143,190,112]);result.writeUInt32BE(result.length-9,5);return result;}
function chunk(){const values=new Uint16Array(65536);for(let x=0;x<16;x++)for(let z=0;z<16;z++)values[64*256+x*16+z]=8;values[68*256+3*16+5]=153;const sections=[];
for(let section=0;section<16;section++){if(section!==4){sections.push(be(0));continue;}const payload=[[0,0,0,0]];for(let channel=0;channel<4;channel++){const runs=[];let i=0;while(i<4096){const v=(values[section*4096+i]>>>(channel*8))&255;let j=i+1;while(j<4096&&((values[section*4096+j]>>>(channel*8))&255)===v)j++;let n=j-i;while(n>255){runs.push(0);n-=255;}runs.push(n,v);i=j;}payload.push(runs);}const data=bytes(...payload);sections.push(be(257),be(data.length),data);}return bytes(be(9),be(-64),be(16),[0,8,16],...sections);}
function chest(body=item(),count=1){return bytes([0,153],be(22+body.length),[1],be(-61),be(68),be(21),[1],be(27),be(count),body);}
function zip(files,compressed=true){const local=[],central=[];let offset=0;for(const [name,input]of files){const data=Buffer.from(input),n=Buffer.from(name),content=compressed?deflateRawSync(data):data,header=Buffer.alloc(30),directory=Buffer.alloc(46),crc=R.crc32(data);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt16LE(compressed?8:0,8);header.writeUInt32LE(crc,14);header.writeUInt32LE(content.length,18);header.writeUInt32LE(data.length,22);header.writeUInt16LE(n.length,26);directory.writeUInt32LE(0x02014b50);directory.writeUInt16LE(20,4);directory.writeUInt16LE(20,6);directory.writeUInt16LE(0x800,8);directory.writeUInt16LE(compressed?8:0,10);directory.writeUInt32LE(crc,16);directory.writeUInt32LE(content.length,20);directory.writeUInt32LE(data.length,24);directory.writeUInt16LE(n.length,28);directory.writeUInt32LE(offset,42);const entry=bytes(header,n,content);local.push(entry);central.push(bytes(directory,n));offset+=entry.length;}const cd=bytes(...central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);return bytes(...local,cd,end);}
test('metadata and v2 player preserve IDs, slot positions, quantities and extra fields',()=>{assert.equal(R.world(metadata()).name,'Test world');const result=R.player(player([item(3157,8,35,true)],[item(3047,1,3,true)]));assert.equal(result.inventory[0].slot,35);assert.equal(result.inventory[0].durability,100);assert.deepEqual(result.inventory[0].enchantments,[{id:7,level:4}]);assert.equal(result.armor[0].itemID,3047);assert.equal(result.level,31);});
test('truncated and ambiguous player layouts never become an empty inventory',()=>{const good=player();for(let n=0;n<good.length;n++)assert.throws(()=>R.player(good.subarray(0,n)));assert.throws(()=>R.player(player([item(),item()])));assert.throws(()=>R.player(player([item(1,0)])));assert.throws(()=>R.player(player([item(1,2,36)])));const empty=R.player(player([],[]));assert.deepEqual(empty.inventory,[]);});
test('chunk coordinates, surface orientation, RLE and chest block cross-check match the native layout',()=>{const b=bytes(chunk(),chest()),c=R.chunk(b,'o.-64,16');assert.equal(c.ids[5*16+3],153);assert.equal(c.heights[5*16+3],68);assert.equal(c.heights[0],64);const rows=R.chests(b,c);assert.equal(rows.length,1);assert.equal(rows[0].x,-61);assert.equal(rows[0].items[0].quantity,12);assert.equal(rows[0].owned,false);assert.throws(()=>R.chunk(b,'o.0,0'));assert.throws(()=>R.chunk(b.subarray(0,30),'o.-64,16'));});
test('unknown and duplicate chest records remain unknown rather than empty',()=>{let b=bytes(chunk(),chest(item(),2));let rows=R.chests(b,R.chunk(b,'o.-64,16'));assert.equal(rows[0].readable,false);b=bytes(chunk(),chest(),chest());rows=R.chests(b,R.chunk(b,'o.-64,16'));assert.equal(rows.length,1);assert.equal(rows[0].readable,false);assert.deepEqual(rows[0].items,[]);});
test('ZIP import supports deflate, replaces content from the selected world and reports missing players',async()=>{const z=new R.Zip(zip([['first/world_data',metadata('First')],['first/o.-64,16',bytes(chunk(),chest())],['first/player_data',player()],['second/world_data',metadata('Second')],['second/o.-64,16',chunk()]]));assert.equal((await z.worlds()).length,2);const first=await z.load('first/'),second=await z.load('second/');assert.equal(first.chests.length,1);assert.equal(second.chests.length,0);assert.equal(second.player,null);assert.equal(second.errors.length,1);assert.equal(first.player.inventory[0].quantity,12);const state=C.fromImport(first,{items:{3157:{de:'Diamant'}},colors:{},blocks:{}},{kind:'local',filename:'test.zip'});assert.equal(state.inventory[0].item,'id:3157');assert.equal(state.chests[0].owned,false);assert.deepEqual(C.totals(state.chests),{});});
test('ZIP traversal, duplicates, truncation and CRC failures are rejected',async()=>{for(const name of ['../world_data','/world_data','dir/../world_data','C:/world_data','a\\world_data'])assert.throws(()=>new R.Zip(zip([[name,metadata()]])));assert.throws(()=>new R.Zip(zip([['a',[1]],['a',[2]]])));const archive=zip([['world_data',metadata()]],false);assert.throws(()=>new R.Zip(archive.subarray(0,-1)));const changed=Buffer.from(archive);changed[40]^=1;const z=new R.Zip(changed);await assert.rejects(()=>z.read('world_data'),/Prüfsumme/);});
test('CRC failure leaves the caller snapshot untouched and real imports retain unknown player state',async()=>{const old=C.initial(),before=structuredClone(old),raw=zip([['world_data',metadata()],['o.-64,16',chunk()]],false);raw[40]^=1;await assert.rejects(()=>new R.Zip(raw).load(''));assert.deepEqual(old,before);const loaded=await new R.Zip(zip([['world_data',metadata()],['o.-64,16',chunk()]],false)).load('');const state=C.fromImport(loaded,{items:{},blocks:{},colors:{}},{kind:'local',filename:'new.zip'});assert.equal(C.snapshot(state).playerStatus,'unknown');assert.equal(state.inventory.filter(Boolean).length,0);assert.equal(C.snapshot(state).source.kind,'local');});
module.exports={metadata,item,player,chunk,chest,zip};
test('sign records support verified wall-sign families and preserve multiline Unicode as plain data',()=>{
 const base=chunk(),c=R.chunk(base,'o.-64,16');c.blocks[69*256+6*16+7]=173;
 function sign(text,marker=162){const content=Buffer.from(text);return bytes([marker>>8,marker&255],be(28+content.length),[1],be(-58),be(69),be(23),[0,1],be(content.length),content,[0,15,0,0,0,0,0,15,0]);}
 const record=sign('Example\nÄΩ <script>');let result=R.signs(bytes(base,record),c);assert.equal(result.length,1);assert.equal(result[0].blockID,173);assert.equal(result[0].text,'Example\nÄΩ <script>');assert.equal(result[0].readable,true);
 result=R.signs(bytes(base,sign('')),c);assert.equal(result[0].readable,true);assert.equal(result[0].text,'');
 for(let n=0;n<record.length;n++){result=R.signs(bytes(base,record.subarray(0,n)),c);assert.equal(result[0].readable,false);}
 result=R.signs(bytes(base,record,record),c);assert.equal(result[0].readable,false);
 const invalid=Buffer.from(record);invalid[25]=255;assert.equal(R.signs(bytes(base,invalid),c)[0].readable,false);
 c.blocks[69*256+6*16+7]=174;assert.equal(R.signs(bytes(base,record),c)[0].readable,false);
});
