'use strict';
const C=DemoCore,$=s=>document.querySelector(s),main=$('#main');
let state=C.initial(),undo=[],catalog=null,recipes=null,guideId='lamp',step=0,selectedSlot=0,transfer=null,dispose=()=>{};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={map:'Karten',chests:'Kisten & Ressourcen',inventory:'Inventar-Sandbox',guides:'Bauanleitungen',recipes:'Rezepte',export:'Kontext-Export'};
const route=()=>Object.hasOwn(titles,location.hash.slice(1))?location.hash.slice(1):'map';
const toast=message=>{$('#toast').textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').textContent='',4000);};
const tags=items=>items.map(s=>`<span class="item-tag">${esc(C.ITEMS[s.item].name)} <b>× ${s.quantity}</b></span>`).join('');
const card=(n,label)=>`<div class="card"><span>${label}</span><strong>${n}</strong></div>`;
const download=(name,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Download erstellt.');};
const projectURL=location.hostname.endsWith('github.io')?`https://github.com/${location.hostname.slice(0,-10)}/${location.pathname.split('/').filter(Boolean)[0]||'RealmCraft-Companion'}`:'https://github.com/search?q=RealmCraft-Companion&type=repositories';
$('#project-link').href=projectURL;
const resetDialog=$('#reset-dialog');$('#reset').onclick=()=>resetDialog.showModal();resetDialog.onclose=()=>{if(resetDialog.returnValue==='reset'){state=C.initial();undo=[];selectedSlot=0;transfer=null;render();toast('Demo zurückgesetzt.');}};
// The footer also exposes attribution and reset on small screens where the sidebar footer is hidden.
$('.page-footer').innerHTML+=' · 100 % mit OpenAI Codex entwickelt / 100% vibe-coded with OpenAI Codex · KI-Contributor: Codex Astra · <a href="'+esc(projectURL)+'">GitHub</a> · <button id="mobile-reset" class="subtle">Demo zurücksetzen</button>';
$('#mobile-reset').onclick=()=>resetDialog.showModal();
function render(){dispose();dispose=()=>{};const view=route();$('#page-title').textContent=titles[view];document.title=`${titles[view]} · RealmCraft Companion Webdemo`;document.querySelectorAll('[data-view]').forEach(a=>{a.classList.toggle('active',a.dataset.view===view);if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});({map:renderMap,chests:renderChests,inventory:renderInventory,guides:renderGuides,recipes:renderRecipes,export:renderExport})[view]();}
window.addEventListener('hashchange',render);
let mapFocus=null;
function renderMap(){
 if(state.worldMap){ImportedMap.render();return;}
 main.innerHTML=`<div class="toolbar"><label>Ansicht <select id="map-mode"><option value="terrain">Landschaft</option><option value="height">Höhenkarte</option></select></label><label><input id="show-chests" type="checkbox" checked> Kisten</label><label><input id="show-grid" type="checkbox"> Chunk-Raster</label><span class="small">128 × 128 Blöcke · Schematische Beispieldaten</span></div><div class="split"><div class="map-wrap"><canvas id="map-canvas" tabindex="0" aria-label="Synthetische Weltkarte. Pfeiltasten verschieben, Plus und Minus zoomen, F setzt die Ansicht zurück. Orte alternativ über Koordinaten auswählen."></canvas><div class="map-badge">◈ DEMO-ARCHIPEL <span class="muted">/ Oberwelt</span></div><div class="map-controls"><button id="zoom-in" aria-label="Vergrößern">+</button><button id="zoom-out" aria-label="Verkleinern">−</button><button id="fit" aria-label="Ganze Karte">⌗</button></div><div class="map-caption"><span id="cursor">X 0 · Z 0</span><span>Ziehen · Zoomen · Ort anklicken</span></div></div><aside class="map-side"><section class="panel"><h2>Ort erkunden</h2><form id="coordinates" class="toolbar"><label>X <input id="coord-x" type="number" value="0" min="-64" max="63" required></label><label>Z <input id="coord-z" type="number" value="0" min="-64" max="63" required></label><button class="primary">Anzeigen</button></form><div id="selection-content"></div><form id="marker-form"><label for="marker-name">Ort merken</label><div class="toolbar"><input id="marker-name" maxlength="50" placeholder="Name des Ortes" required style="width:100%"><button>+ Ort speichern</button></div></form></section><section class="panel"><h2>Meine Orte <span id="marker-count" class="pill">${state.markers.length}</span></h2><ul id="marker-list"></ul><p class="small">Nur in dieser Sitzung. Über Kontext-Export als JSON sichern.</p></section><div class="legend"><span><i style="background:#78a866"></i>Gras</span><span><i style="background:#377e9e"></i>Wasser</span><span><i style="background:#a1aba4"></i>Stein</span><span><i style="background:#f0d18a"></i>Kiste</span></div></aside></div>`;
 const canvas=$('#map-canvas'),ctx=canvas.getContext('2d');let w=0,h=0,zoom=1,panX=0,panZ=0,selected=mapFocus||{x:0,z:0},drag=null;mapFocus=null;
 const scale=()=>Math.min(w,h)/145*zoom;
 const screen=(x,z)=>({x:w/2+(x+panX)*scale(),y:h/2+(z+panZ)*scale()});
 const world=(px,py)=>({x:Math.floor((px-w/2)/scale()-panX),z:Math.floor((py-h/2)/scale()-panZ)});
 function draw(){
 ctx.clearRect(0,0,w,h);const s=scale(),mode=$('#map-mode').value;const colors={grass:[117,160,91],forest:[65,112,77],stone:[155,169,157],water:[52,121,157],sand:[198,182,120]};
 for(let z=-64;z<64;z++)for(let x=-64;x<64;x++){const p=screen(x,z);if(p.x+s<0||p.y+s<0||p.x>w||p.y>h)continue;const t=C.terrain(x,z),shade=1+(t.height-C.terrain(x-1,z).height)*.045;ctx.fillStyle=mode==='height'?`hsl(${210-(t.height-40)*3} 32% ${28+(t.height-40)*.6}%)`:`rgb(${colors[t.type].map(v=>Math.max(0,Math.min(255,Math.round(v*shade)))).join(',')})`;ctx.fillRect(p.x,p.y,s+.5,s+.5);}
 if($('#show-grid').checked){ctx.strokeStyle='#dae8ef55';ctx.lineWidth=1;for(let i=-64;i<=64;i+=16){let p=screen(i,-64),q=screen(i,64);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();p=screen(-64,i);q=screen(64,i);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}
 if($('#show-chests').checked)for(const c of state.chests){const p=screen(c.x+.5,c.z+.5);ctx.fillStyle=c.owned?'#f0d18a':'#dca1ea';ctx.strokeStyle='#1f2621';ctx.lineWidth=2;ctx.fillRect(p.x-6,p.y-6,12,12);ctx.strokeRect(p.x-6,p.y-6,12,12);if(zoom>1.2){ctx.font='13px system-ui';ctx.fillStyle='#0a1720';ctx.fillRect(p.x+10,p.y-12,ctx.measureText(c.name).width+12,22);ctx.fillStyle='#f4f2db';ctx.fillText(c.name,p.x+16,p.y+4);}}
 for(const m of state.markers){const p=screen(m.x+.5,m.z+.5);ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#1f2621';ctx.stroke();}
 const p=screen(selected.x+.5,selected.z+.5);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,11,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x-17,p.y);ctx.lineTo(p.x+17,p.y);ctx.moveTo(p.x,p.y-17);ctx.lineTo(p.x,p.y+17);ctx.stroke();
 }
 function select(p,center=false){selected=p;$('#coord-x').value=p.x;$('#coord-z').value=p.z;if(center){panX=-p.x;panZ=-p.z;}const t=C.terrain(p.x,p.z),c=state.chests.find(c=>c.x===p.x&&c.z===p.z);const names={grass:'Grasland',forest:'Wald',water:'Wasser',sand:'Sandufer',stone:'Steinrücken'};$('#selection-content').innerHTML=`<p class="coordinates">X ${p.x} · Y ${t.height} · Z ${p.z}</p><p>${names[t.type]} <span class="small">· synthetische Oberfläche</span></p>${c?`<h3>${esc(c.name)}</h3><p class="small">Kiste bei Y ${c.y} · ${c.owned?'Als eigene markiert':'Eigentum unbekannt'}</p><div class="item-tags">${tags(c.items)}</div><p><a href="#chests">Kisten durchsuchen →</a></p>`:''}`;draw();}
 function markerList(){const ul=$('#marker-list');ul.replaceChildren();for(const [i,m] of state.markers.entries()){const li=document.createElement('li'),a=document.createElement('button'),b=document.createElement('button');a.textContent=m.name;a.className='subtle';a.onclick=()=>select(m,true);b.textContent='×';b.className='marker-remove';b.setAttribute('aria-label',`${m.name} entfernen`);b.onclick=()=>{state.markers.splice(i,1);markerList();draw();};li.append(a,b);ul.append(li);}if(!state.markers.length)ul.innerHTML='<li class="muted">Noch keine Orte gespeichert.</li>';$('#marker-count').textContent=state.markers.length;}
 function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;canvas.width=Math.round(w*devicePixelRatio);canvas.height=Math.round(h*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);draw();}
 const observer=new ResizeObserver(resize);observer.observe(canvas);dispose=()=>observer.disconnect();
 function changeZoom(f){zoom=Math.max(.6,Math.min(8,zoom*f));draw();}$('#zoom-in').onclick=()=>changeZoom(1.35);$('#zoom-out').onclick=()=>changeZoom(1/1.35);$('#fit').onclick=()=>{panX=panZ=0;zoom=1;draw();};$('#map-mode').onchange=draw;$('#show-chests').onchange=draw;$('#show-grid').onchange=draw;
 canvas.onwheel=e=>{e.preventDefault();changeZoom(e.deltaY<0?1.1:1/1.1);};
 canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,px:panX,pz:panZ,moved:false};canvas.setPointerCapture(e.pointerId);};
 canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect(),p=world(e.clientX-r.left,e.clientY-r.top);$('#cursor').textContent=`X ${p.x} · Z ${p.z}`;if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>4)drag.moved=true;panX=drag.px+dx/scale();panZ=drag.pz+dy/scale();draw();}};
 canvas.onpointerup=e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),p=world(e.clientX-r.left,e.clientY-r.top);if(p.x>=-64&&p.x<64&&p.z>=-64&&p.z<64)select(p);}drag=null;};canvas.onpointercancel=()=>drag=null;
 canvas.onkeydown=e=>{let handled=true;if(e.key==='+')changeZoom(1.2);else if(e.key==='-')changeZoom(1/1.2);else if(e.key.toLowerCase()==='f')$('#fit').click();else if(e.key==='ArrowLeft')panX+=5;else if(e.key==='ArrowRight')panX-=5;else if(e.key==='ArrowUp')panZ+=5;else if(e.key==='ArrowDown')panZ-=5;else handled=false;if(handled){e.preventDefault();draw();}};
 $('#coordinates').onsubmit=e=>{e.preventDefault();select({x:Number($('#coord-x').value),z:Number($('#coord-z').value)},true);};
 $('#marker-form').onsubmit=e=>{e.preventDefault();const name=$('#marker-name').value.trim();if(!name)return;state.markers.push({...selected,name});$('#marker-name').value='';markerList();draw();toast('Ort gespeichert.');};markerList();resize();select(selected);
}
function renderChests(){
 const total=C.totals(state.chests);main.innerHTML=`<div class="cards">${card(state.chests.length,state.source?'Eingelesene Kisten':'Beispielkisten')}${card(state.chests.filter(c=>c.owned).length,'Als eigene markiert')}${card(Object.keys(total).length,'Materialarten im eigenen Lager')}${card(Object.values(total).reduce((a,b)=>a+b,0),'Gegenstände im eigenen Lager')}</div>${state.errors?.length?'<div class="notice">Teilweise lesbarer Datenstand: '+state.errors.length+' Lesehinweis(e). Nicht lesbare Kisten zählen nicht als leere Kisten.</div>':''}${state.source?'<p class="small">Eigentum ist zunächst unbekannt. Markiere deine Kisten ausdrücklich als eigene, um Materialvorräte zu vergleichen.</p>':''}<div class="toolbar"><input id="chest-query" type="search" aria-label="Kisten durchsuchen" placeholder="Kiste, Material oder Koordinaten suchen …"><label><input id="owned-only" type="checkbox"> Nur eigene Kisten</label><span id="chest-count" class="small" role="status"></span></div><div id="chest-results" class="result-list"></div><section class="panel" style="margin-top:20px"><h2>Materialvorrat · eigene Kisten</h2>${Object.keys(total).length?'':'<p class="small">Kein lesbarer eigener Lagerbestand erfasst. Markiere eigene Kisten, um hier ihre Materialien zu sehen.</p>'}<div class="resource-bars">${Object.entries(total).sort((a,b)=>b[1]-a[1]).map(([id,n])=>`<div class="resource-row"><span>${C.ITEMS[id].name}</span><div class="resource-bar"><span style="width:${n/Math.max(...Object.values(total))*100}%"></span></div><b>${n}</b></div>`).join('')}</div></section>`;
 function results(){const found=C.filterChests(state.chests,$('#chest-query').value,$('#owned-only').checked);$('#chest-count').textContent=`${found.length} von ${state.chests.length} Kisten`;$('#chest-results').innerHTML=found.length?found.map(c=>`<article class="panel chest"><div><h2>${esc(c.name)}</h2><span class="coordinates">${c.dimension?c.dimension==='n'?'Nether · ':'Oberwelt · ':''}X ${c.x} · Y ${c.y} · Z ${c.z}</span><div class="toolbar"><label><input type="checkbox" data-owned="${c.id}" ${c.owned?'checked':''}> Eigene Kiste</label><button data-locate="${c.id}">Auf Karte ↗</button></div></div><div class="item-tags">${c.readable===false?'<p class="notice">Inhalt nicht lesbar; Bestand unbekannt.</p>':c.items.length?tags(c.items):'<p class="small">Kiste ist leer.</p>'}</div></article>`).join(''):'<div class="empty">Keine Kiste passt zur Suche. Versuche einen anderen Begriff.</div>';document.querySelectorAll('[data-locate]').forEach(b=>b.onclick=()=>{mapFocus=state.chests.find(c=>c.id===b.dataset.locate);location.hash='map';});document.querySelectorAll('[data-owned]').forEach(b=>b.onchange=()=>{const q=$('#chest-query').value,o=$('#owned-only').checked;state.chests.find(c=>c.id===b.dataset.owned).owned=b.checked;renderChests();$('#chest-query').value=q;$('#owned-only').checked=o;$('#chest-query').dispatchEvent(new Event('input'));toast('Eigentumsmarkierung und Vorrat aktualisiert.');});}
 $('#chest-query').oninput=results;$('#owned-only').onchange=results;results();
}
function renderInventory(){
 if(state.playerStatus==='unknown'){main.innerHTML='<div class="notice">Spielerdaten fehlen oder sind nicht lesbar. Inventar und Level sind unbekannt.</div>';return;}
 const selected=state.inventory[selectedSlot];main.innerHTML=`<div class="notice">${state.source?'Sandbox auf Basis der geladenen ZIP. Änderungen betreffen nur die Ansicht im Browser; die ZIP bleibt unverändert. Es entsteht kein spielbarer Savegame-Export.':'Sandbox mit Beispieldaten. Mengen, Duplikate und Verschiebungen verändern ausschließlich diese Demo. Es wird kein RealmCraft-Spielstand bearbeitet.'}</div><div class="toolbar"><button id="undo" ${undo.length?'':'disabled'}>↶ Rückgängig</button><button id="sort">Nach Gegenstand sortieren</button><span class="small">${state.inventory.filter(Boolean).length} / 36 Slots belegt</span></div><div class="inventory-layout"><section class="panel"><h2>Rucksack <span class="small">/ 36 Slots${state.source?' · Level '+(state.level??'unbekannt'):''}</span></h2><div class="slots">${state.inventory.map((s,i)=>`<button class="slot ${selectedSlot===i?'selected':''} ${transfer&&!s?'target':''}" data-slot="${i}" aria-label="Slot ${i+1}: ${s?`${C.ITEMS[s.item].name}, ${s.quantity}`:'leer'}" aria-pressed="${selectedSlot===i}"><span class="slotnum">${i+1}</span>${s?`<span class="symbol" style="color:${C.ITEMS[s.item].color}">${C.ITEMS[s.item].symbol}</span><b class="qty">${s.quantity}</b>`:'<span class="slot-empty">·</span>'}</button>`).join('')}</div><p class="small" style="margin:18px 0 0">${transfer?'Wähle jetzt einen freien, gestrichelt umrandeten Zielslot.':'Gegenstand anklicken, dann eine Aktion wählen.'}</p></section><section class="panel"><h2>${selected?C.ITEMS[selected.item].name:'Leerer Slot'}</h2><p class="small">Slot ${selectedSlot+1}${selected?` · Menge ${selected.quantity}`:''}</p>${selected?`<div class="editor-actions"><form id="quantity-form"><label for="quantity">Neue Menge (1–64)</label><div class="toolbar"><input id="quantity" type="number" min="1" max="64" step="1" required value="${selected.quantity}"><button class="primary">Anwenden</button></div></form><button id="move">In freien Slot verschieben</button><button id="duplicate">In freien Slot duplizieren</button>${transfer?'<button id="cancel-transfer">Zielauswahl abbrechen</button>':''}</div>`:'<p>Wähle einen belegten Slot, um Gegenstände zu bearbeiten.</p>'}</section></div>`;
 function apply(action,options={}){try{const next=C.editInventory(state.inventory,action,selectedSlot,options);undo.push(structuredClone(state.inventory));state.inventory=next;if(Number.isInteger(options.target))selectedSlot=options.target;transfer=null;renderInventory();toast('Beispielinventar aktualisiert.');}catch(e){toast(e.message);}}
 document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.slot);if(transfer){if(state.inventory[i]){toast('Bitte einen freien Zielslot wählen.');return;}apply(transfer,{target:i});}else{selectedSlot=i;renderInventory();}});
 if(selected){$('#quantity-form').onsubmit=e=>{e.preventDefault();apply('quantity',{quantity:Number($('#quantity').value)});};$('#move').onclick=()=>{transfer='move';renderInventory();};$('#duplicate').onclick=()=>{transfer='duplicate';renderInventory();};if($('#cancel-transfer'))$('#cancel-transfer').onclick=()=>{transfer=null;renderInventory();};}
 $('#sort').onclick=()=>apply('sort');$('#undo').onclick=()=>{if(undo.length){state.inventory=undo.pop();transfer=null;renderInventory();toast('Letzte Inventaränderung rückgängig gemacht.');}};
}
async function getData(name){const response=await fetch(`data/${name}.json`);if(!response.ok)throw Error('Katalog konnte nicht geladen werden.');return response.json();}
function loadError(retry){main.innerHTML='<div class="empty"><p>Die Daten konnten nicht geladen werden. Bitte prüfe die Verbindung.</p><button id="retry">Erneut versuchen</button></div>';$('#retry').onclick=retry;}
function plane(p,highlight=[]){if(!p)return '';return `<div class="diagram"><h3>${esc(p.title.de)}</h3><table class="grid-plane" aria-label="${esc(p.title.de)}"><thead><tr><th>${esc(p.rowAxis)} / ${esc(p.columnAxis)}</th>${p.columns.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${p.cells.map((row,r)=>`<tr><th>${esc(p.rows[r])}</th>${row.map((v,c)=>`<td tabindex="0" title="${esc(catalog.blocks[v]?.name.de||v)}" aria-label="${esc(catalog.blocks[v]?.name.de||v)}" class="${v==='.'?'air':''} ${highlight.includes(`${r}:${c}`)?'new':''}">${esc(v==='.'?'·':v)}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="small">${esc(p.note.de)}</p></div>`;}
async function renderGuides(){
 if(!catalog){main.innerHTML='<p role="status">Bauanleitungen werden geladen …</p>';try{catalog=await getData('BuildGuides');}catch{if(route()==='guides')loadError(renderGuides);return;}if(route()!=='guides')return;}
 const guide=catalog.guides.find(g=>g.id===guideId)||catalog.guides[0];guideId=guide.id;step=Math.min(step,guide.steps.length-1);const stage=guide.instructionStages?.[step];
 main.innerHTML=`<div class="guide-layout"><aside><label for="guide-search">${catalog.guides.length} Anleitungen durchsuchen</label><input id="guide-search" type="search" placeholder="Titel suchen …" style="width:100%;margin:10px 0"><div class="guide-list">${catalog.guides.map(g=>`<button data-guide="${esc(g.id)}" class="${g.id===guideId?'active':''}">${esc(g.title.de)}</button>`).join('')}</div><p id="guide-empty" class="small" hidden>Keine passende Anleitung.</p></aside><article class="panel"><span class="eyebrow">ANLEITUNGSBUCH / ${esc(guide.footprint.de)}</span><h2 style="margin-top:12px;font-size:1.6rem">${esc(guide.title.de)}</h2><p class="muted">${esc(guide.summary.de)}</p><div class="notice">${esc(guide.evidence.de)}</div><h3>Einkaufsliste</h3><div class="checklist">${guide.materials.map((m,i)=>`<label><input type="checkbox" data-check="${i}" ${state.checks[`${guideId}:${i}`]?'checked':''}> ${esc(m.count.de)} × ${esc(m.name.de)}</label>`).join('')}</div><div class="toolbar"><button id="step-prev" ${step===0?'disabled':''}>← Zurück</button><span role="status">Schritt ${step+1} von ${guide.steps.length}</span><button id="step-next" ${step===guide.steps.length-1?'disabled':''}>Weiter →</button></div><div class="progress-track"><span style="width:${(step+1)/guide.steps.length*100}%"></span></div><p class="step-text">${esc(guide.steps[step].de)}</p><div class="diagrams">${stage?plane(stage.top,stage.topNew)+plane(stage.side,stage.sideNew):(guide.planes||[]).map(p=>plane(p)).join('')}</div><details><summary>Zeichenlegende</summary><div class="item-tags" style="margin-top:12px">${Object.entries(catalog.blocks).filter(([k])=>JSON.stringify(stage||guide.planes).includes('"'+k+'"')).map(([k,v])=>`<span class="item-tag"><b>${esc(k)}</b> ${esc(v.name.de)}</span>`).join('')}</div></details><h3 style="margin-top:24px">Erwartetes Ergebnis</h3><p>${esc(guide.success.de)}</p><details><summary>Wenn es nicht funktioniert</summary><p style="margin-top:14px">${esc(guide.troubleshooting.de)}</p></details><div class="source-links">${guide.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`).join('')}</div></article></div>`;
 document.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>{guideId=b.dataset.guide;step=0;renderGuides();});document.querySelectorAll('[data-check]').forEach(b=>b.onchange=()=>{state.checks[`${guideId}:${b.dataset.check}`]=b.checked;});$('#step-prev').onclick=()=>{step--;renderGuides();};$('#step-next').onclick=()=>{step++;renderGuides();};$('#guide-search').oninput=()=>{const q=$('#guide-search').value.toLocaleLowerCase();let count=0;document.querySelectorAll('[data-guide]').forEach(b=>{b.hidden=!b.textContent.toLocaleLowerCase().includes(q);if(!b.hidden)count++;});$('#guide-empty').hidden=count>0;};
}
async function renderRecipes(){
 if(!recipes){main.innerHTML='<p role="status">Rezepte werden geladen …</p>';try{recipes=await getData('ConversationRecipes');}catch{if(route()==='recipes')loadError(renderRecipes);return;}if(route()!=='recipes')return;}
 main.innerHTML=`<div class="notice">Referenzwissen aus dem Companion. Die Quellen und der jeweilige Prüfstatus stehen bei jedem Rezept. Materialchecks berücksichtigen nur als eigene markierte Kisten.</div><section class="panel" style="margin-bottom:20px"><h2>Materialcheck ausprobieren</h2><div class="toolbar"><label>Referenzrezept <select id="check-recipe"><option value="bed">Bett · 3 Bretter + 3 weiße Wolle</option><option value="table">Werkbank · 4 Bretter</option></select></label><label>Anzahl <input id="check-count" type="number" min="1" max="64" step="1" value="1"></label></div><div id="check-result" class="item-tags" role="status"></div><p class="small" style="margin:14px 0 0">Minecraft-Referenz; RealmCraft-Rezept im Spiel prüfen. Keine Zwischenprodukte oder Inventarbestände eingerechnet.</p></section><div class="toolbar"><input id="recipe-search" type="search" placeholder="Rezept suchen …" aria-label="Rezepte durchsuchen"><span id="recipe-count" class="small" role="status"></span></div><div id="recipe-results" class="recipe-grid"></div>`;
 function check(){try{const rows=C.assessment($('#check-recipe').value,state.chests,Number($('#check-count').value));$('#check-result').innerHTML=rows.map(r=>`<span class="item-tag">${C.ITEMS[r.item].name}: ${r.available} vorhanden / ${r.needed} benötigt · <b>${r.missing?`${r.missing} fehlen`:'ausreichend'}</b></span>`).join('');}catch(e){$('#check-result').textContent=e.message;}}
 function results(){const q=$('#recipe-search').value.toLocaleLowerCase(),found=recipes.filter(r=>(r.title.de+' '+r.title.en+' '+r.aliases.join(' ')).toLocaleLowerCase().includes(q));$('#recipe-count').textContent=`${found.length} Rezepte`;$('#recipe-results').innerHTML=found.length?found.map(r=>`<article class="panel"><h2>${esc(r.title.de)}</h2><p>${esc(r.materials.de)}</p><p class="muted">${esc(r.steps.de)}</p><p class="small">${esc(r.evidence.de)}</p><a href="${esc(r.source.url)}" target="_blank" rel="noopener noreferrer">${esc(r.source.title)} ↗</a></article>`).join(''):'<p class="empty">Kein passendes Rezept gefunden.</p>';}
 $('#check-recipe').onchange=check;$('#check-count').oninput=check;$('#recipe-search').oninput=results;check();results();
}
function renderExport(){
 const data=C.snapshot(state),json=JSON.stringify(data,null,2);const markdown=['# RealmCraft Companion · Browser-Demokontext','',`Source: ${state.source?state.source.kind==='demo'?'Published demonstration ZIP':'Locally selected ZIP; not uploaded':'Synthetic demonstration; no real savegame data'}.`,'',...(state.source?[`World: ${state.source.name}`,`Player data: ${state.playerStatus}`,`Level: ${state.level??'unknown'}`,`Read issues: ${state.errors.length}`]:[]),'',state.source?'## Inventar':'## Beispielinventar',...data.inventory.map((s,i)=>s?`- Slot ${i+1}: ${C.ITEMS[s.item].name} × ${s.quantity}`:null).filter(Boolean),'',state.source?'## Kisten':'## Beispielkisten',...data.chests.flatMap(c=>[`### ${c.name}`,`Readable: ${c.readable===false?'no; contents unknown':'yes'}`,`Coordinates: ${c.x}, ${c.y}, ${c.z}. Ownership: ${c.owned?'marked owned':'unknown'}.`,...c.items.map(s=>`- ${C.ITEMS[s.item].name} × ${s.quantity}`)]),'','## Eigene Orte',...data.markers.map(m=>`- ${m.name.replace(/[\r\n]/g,' ')}: ${m.dimension||'o'} · X ${m.x}, Z ${m.z}`)].join('\n');
 main.innerHTML=`<div class="notice">Dieser Export enthält den aktuellen Datenstand${state.source?' aus der geladenen ZIP und deine Änderungen im Browser':' der Webdemo'}. Es wird kein KI-Dienst aufgerufen und nichts automatisch hochgeladen. Du kannst die Datei selbst in einem Chat verwenden.</div><div class="cards">${card(state.playerStatus==='unknown'?'unbekannt':data.inventory.filter(Boolean).length,'Belegte Inventarslots')}${card(data.chests.length,'Kisten im Export')}${card(data.markers.length,'Eigene Orte')}${card(Object.keys(data.ownedStorageTotals).length,'Eigene Materialarten')}</div><section class="panel"><div class="toolbar"><label>Vorschau <select id="export-format"><option value="markdown">Markdown</option><option value="json">JSON</option></select></label><button id="download-md" class="primary">Markdown herunterladen ↓</button><button id="download-json">JSON herunterladen ↓</button></div><label for="export-preview">Vollständiger Kontext</label><textarea id="export-preview" class="export-preview" readonly></textarea><p class="small" style="margin:14px 0 0">${state.source?'Die Dateien enthalten gelesene Spielstanddaten und deine Änderungen aus dieser Sitzung.':'Die Dateien enthalten Beispieldaten und deine Änderungen aus dieser Sitzung.'} Eigene Lagerbestände werden getrennt vom Inventar und von Kisten unbekannten Eigentums ausgewiesen.</p></section>`;
 $('#export-preview').value=markdown;$('#export-format').onchange=()=>$('#export-preview').value=$('#export-format').value==='json'?json:markdown;$('#download-md').onclick=()=>download('companion-webdemo-context.md',markdown,'text/markdown;charset=utf-8');$('#download-json').onclick=()=>download('companion-webdemo-context.json',json,'application/json');
}
render();
