'use strict';
window.ImportedMap=(function(){
let dimension='o',textures=new WeakMap();
function reset(){dimension='o';textures=new WeakMap();}
function render(){
 const world=state.worldMap,hadFocus=!!mapFocus;
 if(mapFocus?.dimension)dimension=mapFocus.dimension;
 if(!world.dimensions[dimension])dimension=Object.keys(world.dimensions)[0];
 const d=world.dimensions[dimension],bounds=d.bounds,chunks=new Map(d.chunks.map(c=>[I18n.html`${c.x},${c.z}`,c]));
 let selected=mapFocus||{x:d.chunks[0].x,z:d.chunks[0].z},width=1,height=1,zoom=1,panX=0,panZ=0,drag=null;mapFocus=null;let pointControls=null;
 main.innerHTML=I18n.html`<div class="toolbar"><label>Dimension <select id="real-dimension">${Object.keys(world.dimensions).map(id=>I18n.html`<option value="${id}" ${id===dimension?'selected':''}>${id==='o'?I18n.t('Oberwelt'):'Nether'}</option>`).join('')}</select></label><label>Ansicht <select id="real-mode"><option value="terrain">Landschaft</option><option value="height">Höhenkarte</option></select></label><label><input id="real-chests" type="checkbox" checked> Kisten</label><label><input id="real-signs" type="checkbox" checked> Schilder</label><label><input id="real-grid" type="checkbox"> Chunk-Raster</label><span class="small">${d.chunks.length} gespeicherte Chunks</span></div>${state.errors.length?I18n.html`<div class="notice">${state.errors.length} Lesehinweis(e). Die Karte zeigt nur lesbare Chunks; unbekannte Bereiche bleiben frei.</div>`:''}<div class="split"><div class="map-wrap"><canvas id="real-map" tabindex="0" aria-label="Karte der geladenen ZIP. Pfeiltasten verschieben, Plus und Minus zoomen, F zeigt die ganze Karte. Koordinaten können im Formular ausgewählt werden."></canvas><div class="map-badge">${esc(world.metadata.name)}</div><div class="map-controls"><button id="real-plus" aria-label="Vergrößern">+</button><button id="real-minus" aria-label="Verkleinern">−</button><button id="real-fit" aria-label="Ganze Karte">⌗</button></div><div class="map-caption"><span id="real-cursor">Gespeicherte Welt</span><span>Ziehen · Scrollen · Ort anklicken</span></div></div><aside class="map-side"><section class="panel" id="points-panel"></section><section class="panel"><h2>Ort erkunden</h2><form id="real-locate" class="toolbar"><label>X <input id="real-x" type="number" step="1" required min="${bounds[0]}" max="${bounds[2]-1}" value="${selected.x}"></label><label>Z <input id="real-z" type="number" step="1" required min="${bounds[1]}" max="${bounds[3]-1}" value="${selected.z}"></label><button class="primary">Anzeigen</button></form><div id="real-selection"></div><form id="real-marker"><label for="real-name">Ort merken</label><div class="toolbar"><input id="real-name" maxlength="50" required placeholder="Name des Ortes" style="width:100%"><button>+ Ort speichern</button></div></form></section><section class="panel"><h2>Meine Orte</h2><ul id="real-markers"></ul><p class="small">${dimension==='n'?I18n.t('Nether: oberster Block bis Y 90; Dach ausgeblendet.'):I18n.t('Gespeicherte Oberfläche mit schematischen Blockfarben.')} Kisten aller Höhen werden angezeigt. Kein Nachweis für besuchte Bereiche.</p></section></aside></div>`;
 const canvas=$('#real-map'),ctx=canvas.getContext('2d');
 const scale=()=>Math.min(width/(bounds[2]-bounds[0]+16),height/(bounds[3]-bounds[1]+16))*zoom;
 const screen=(x,z)=>({x:width/2+(x-(bounds[0]+bounds[2])/2+panX)*scale(),y:height/2+(z-(bounds[1]+bounds[3])/2+panZ)*scale()});
 const coordinate=(x,y)=>({x:Math.floor((x-width/2)/scale()+(bounds[0]+bounds[2])/2-panX),z:Math.floor((y-height/2)/scale()+(bounds[1]+bounds[3])/2-panZ)});
 const cell=(x,z)=>{const c=chunks.get(I18n.html`${Math.floor(x/16)*16},${Math.floor(z/16)*16}`);if(!c)return null;const i=(z-c.z)*16+x-c.x;return {id:c.ids[i],y:c.heights[i]};};
 function texture(c,mode){
 let cached=textures.get(c);if(!cached){cached={};textures.set(c,cached);}if(cached[mode])return cached[mode];
 const tile=document.createElement('canvas');tile.width=tile.height=16;const t=tile.getContext('2d');
 for(let z=0;z<16;z++)for(let x=0;x<16;x++){const i=z*16+x,id=c.ids[i];if(id===0||id===639)continue;const y=c.heights[i];t.fillStyle=mode==='height'?I18n.html`hsl(${210-y*.6} 32% ${25+y*.2}%)`:(world.catalog.colors[id]||'#db5bc0');t.fillRect(x,z,1,1);if(x&&mode!=='height'){const slope=y-c.heights[i-1];if(slope){t.fillStyle=slope>0?I18n.html`rgba(255,255,255,${Math.min(.22,slope*.025)})`:I18n.html`rgba(0,0,0,${Math.min(.3,-slope*.04)})`;t.fillRect(x,z,1,1);}}}
 cached[mode]=tile;return tile;
 }
 function draw(){
 ctx.clearRect(0,0,width,height);ctx.imageSmoothingEnabled=false;const s=scale(),mode=$('#real-mode').value;
 for(const c of d.chunks){const p=screen(c.x,c.z);if(p.x+16*s<0||p.y+16*s<0||p.x>width||p.y>height)continue;ctx.drawImage(texture(c,mode),p.x,p.y,16*s,16*s);if($('#real-grid').checked){ctx.strokeStyle='#dce4d644';ctx.lineWidth=1;ctx.strokeRect(p.x,p.y,16*s,16*s);}}
 if($('#real-chests').checked)for(const c of state.chests.filter(c=>c.dimension===dimension)){const p=screen(c.x+.5,c.z+.5);ctx.fillStyle=c.readable===false?'#ed8983':c.owned?'#a8cf6e':'#f0d18a';ctx.fillRect(p.x-5,p.y-5,10,10);ctx.strokeStyle='#131a17';ctx.strokeRect(p.x-5,p.y-5,10,10);}
 if($('#real-signs').checked)for(const sign of (state.signs||[]).filter(s=>s.dimension===dimension)){const p=screen(sign.x+.5,sign.z+.5);ctx.fillStyle='#f2c57d';ctx.strokeStyle='#131a17';ctx.lineWidth=2;ctx.fillRect(p.x-7,p.y-9,14,10);ctx.strokeRect(p.x-7,p.y-9,14,10);ctx.beginPath();ctx.moveTo(p.x,p.y+1);ctx.lineTo(p.x,p.y+7);ctx.stroke();}
 for(const m of state.markers.filter(m=>m.dimension===dimension)){const p=screen(m.x+.5,m.z+.5);ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();}
 const p=screen(selected.x+.5,selected.z+.5);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,10,0,Math.PI*2);ctx.stroke();
 }
 function select(p,center=false){selected={x:p.x,z:p.z,dimension};if(center){panX=(bounds[0]+bounds[2])/2-p.x;panZ=(bounds[1]+bounds[3])/2-p.z;}$('#real-x').value=p.x;$('#real-z').value=p.z;const c=cell(p.x,p.z),chests=state.chests.filter(t=>t.dimension===dimension&&t.x===p.x&&t.z===p.z);$('#real-selection').innerHTML=I18n.html`<p class="coordinates">X ${p.x} · ${c?'Y '+c.y+' · ':''}Z ${p.z}</p><p>${c?esc(world.catalog.items[String(c.id)]?.[I18n.language]||world.catalog.blocks[c.id]||'Block #'+c.id):I18n.t('Kein lesbarer Chunk an diesem Ort.')}</p>${chests.map(t=>I18n.html`<h3>Kiste · Y ${t.y}</h3>${t.readable?I18n.html`<div class="item-tags">${tags(t.items)}</div>`:I18n.t('<p class="notice">Kisteninhalt unbekannt.</p>')}`).join('')}`;const found=(state.signs||[]).filter(s=>s.dimension===dimension&&s.x===p.x&&s.z===p.z);for(const sign of found){const title=document.createElement('h3');title.textContent=I18n.t('Schild')+' · Y '+sign.y;const text=document.createElement('pre');text.className='sign-text';text.textContent=sign.readable?(sign.text||I18n.t('Leere Beschriftung')):I18n.t('Beschriftung nicht verfügbar');$('#real-selection').append(title,text);}draw();}
 function markers(){const list=$('#real-markers');list.replaceChildren();for(const m of state.markers.filter(m=>m.dimension===dimension)){const li=document.createElement('li'),go=document.createElement('button'),remove=document.createElement('button');go.textContent=m.name;go.className='subtle';go.onclick=()=>select(m,true);remove.textContent='×';remove.setAttribute('aria-label',m.name+I18n.t(' entfernen'));remove.onclick=()=>{state.markers.splice(state.markers.indexOf(m),1);markers();pointControls?.refresh(false);draw();};li.append(go,remove);list.append(li);}if(!list.children.length)list.innerHTML=I18n.t('<li class="small">Noch keine Orte gespeichert.</li>');}
 function resize(){const r=canvas.getBoundingClientRect();width=r.width;height=r.height;canvas.width=Math.round(width*devicePixelRatio);canvas.height=Math.round(height*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);draw();}
 const observer=new ResizeObserver(resize);observer.observe(canvas);dispose=()=>observer.disconnect();
 const zoomBy=f=>{zoom=Math.max(.5,Math.min(128,zoom*f));draw();};$('#real-plus').onclick=()=>zoomBy(1.4);$('#real-minus').onclick=()=>zoomBy(1/1.4);$('#real-fit').onclick=()=>{zoom=1;panX=panZ=0;draw();};$('#real-mode').onchange=draw;$('#real-grid').onchange=draw;$('#real-chests').onchange=draw;$('#real-signs').onchange=draw;$('#real-dimension').onchange=()=>{dimension=$('#real-dimension').value;dispose();render();};
 canvas.onwheel=e=>{e.preventDefault();zoomBy(e.deltaY<0?1.1:1/1.1);};
 canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,px:panX,pz:panZ,moved:false};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect(),p=coordinate(e.clientX-r.left,e.clientY-r.top);$('#real-cursor').textContent=I18n.html`X ${p.x} · Z ${p.z}`;if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved||=Math.hypot(dx,dy)>4;panX=drag.px+dx/scale();panZ=drag.pz+dy/scale();draw();}};canvas.onpointerup=e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect();select(coordinate(e.clientX-r.left,e.clientY-r.top));}drag=null;};canvas.onpointercancel=()=>drag=null;
 canvas.onkeydown=e=>{let handled=true;if(e.key==='+')zoomBy(1.2);else if(e.key==='-')zoomBy(1/1.2);else if(e.key.toLowerCase()==='f')$('#real-fit').click();else if(e.key==='ArrowLeft')panX+=20/scale();else if(e.key==='ArrowRight')panX-=20/scale();else if(e.key==='ArrowUp')panZ+=20/scale();else if(e.key==='ArrowDown')panZ-=20/scale();else handled=false;if(handled){e.preventDefault();draw();}};
 $('#real-locate').onsubmit=e=>{e.preventDefault();select({x:Number($('#real-x').value),z:Number($('#real-z').value)},true);};$('#real-marker').onsubmit=e=>{e.preventDefault();const name=$('#real-name').value.trim();if(!name)return;state.markers.push({...selected,name});$('#real-name').value='';markers();pointControls?.refresh(false);draw();};markers();resize();select(selected);pointControls=Points.mount($('#points-panel'),state,dimension,p=>select(p,true),{selectFirst:!hadFocus});
}
return {render,reset};
})();
